-- =============================================================
-- Keystone Field Service Management — Supabase setup
-- Paste this entire script into Supabase → SQL Editor and run.
-- Safe to re-run: all CREATE statements use IF NOT EXISTS.
-- =============================================================

-- ==================== SCHEMA ====================

CREATE SEQUENCE IF NOT EXISTS work_order_number_seq START WITH 100;

CREATE TABLE IF NOT EXISTS users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(100) NOT NULL UNIQUE,
    password     VARCHAR(255) NOT NULL,
    first_name   VARCHAR(100) NOT NULL,
    last_name    VARCHAR(100) NOT NULL,
    email        VARCHAR(150) NOT NULL UNIQUE,
    phone        VARCHAR(30),
    role         VARCHAR(30)  NOT NULL,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ  NOT NULL
);

CREATE TABLE IF NOT EXISTS customers (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(200) NOT NULL UNIQUE,
    contact_name VARCHAR(100),
    email        VARCHAR(150),
    phone        VARCHAR(30),
    address      VARCHAR(300),
    user_id      BIGINT REFERENCES users(id),
    created_at   TIMESTAMPTZ  NOT NULL,
    updated_at   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_customers_user UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS sites (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    BIGINT       NOT NULL REFERENCES customers(id),
    name           VARCHAR(200) NOT NULL,
    street_address VARCHAR(200) NOT NULL,
    city           VARCHAR(100) NOT NULL,
    state          VARCHAR(50),
    zip            VARCHAR(20),
    country        VARCHAR(100),
    contact_name   VARCHAR(100),
    contact_phone  VARCHAR(30),
    notes          VARCHAR(500),
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sites_customer ON sites(customer_id);

CREATE TABLE IF NOT EXISTS work_orders (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_number      VARCHAR(30)  NOT NULL UNIQUE,
    customer_id            BIGINT       NOT NULL REFERENCES customers(id),
    site_id                BIGINT       NOT NULL REFERENCES sites(id),
    title                  VARCHAR(200) NOT NULL,
    description            VARCHAR(2000),
    priority               VARCHAR(20)  NOT NULL,
    status                 VARCHAR(20)  NOT NULL DEFAULT 'NEW',
    assigned_technician_id BIGINT       REFERENCES users(id),
    created_by_id          BIGINT       REFERENCES users(id),
    scheduled_start        TIMESTAMP,
    scheduled_end          TIMESTAMP,
    actual_start           TIMESTAMP,
    actual_end             TIMESTAMP,
    sla_due_at             TIMESTAMP,
    sla_breached           BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMPTZ  NOT NULL,
    updated_at             TIMESTAMPTZ  NOT NULL,
    closed_at              TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_wo_status     ON work_orders(status);
CREATE INDEX IF NOT EXISTS idx_wo_customer   ON work_orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_wo_technician ON work_orders(assigned_technician_id);

CREATE TABLE IF NOT EXISTS work_order_status_history (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id  BIGINT      NOT NULL REFERENCES work_orders(id),
    from_status    VARCHAR(20),
    to_status      VARCHAR(20) NOT NULL,
    changed_by_id  BIGINT      REFERENCES users(id),
    changed_at     TIMESTAMPTZ NOT NULL,
    note           VARCHAR(1000)
);
CREATE INDEX IF NOT EXISTS idx_woh_work_order ON work_order_status_history(work_order_id);

CREATE TABLE IF NOT EXISTS parts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku              VARCHAR(50)    NOT NULL UNIQUE,
    name             VARCHAR(200)   NOT NULL,
    description      VARCHAR(1000),
    unit_price       NUMERIC(19, 2) NOT NULL,
    quantity_on_hand INTEGER        NOT NULL DEFAULT 0,
    reorder_level    INTEGER        NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ    NOT NULL,
    updated_at       TIMESTAMPTZ    NOT NULL
);

CREATE TABLE IF NOT EXISTS stock_movements (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id         BIGINT      NOT NULL REFERENCES parts(id),
    work_order_id   BIGINT      REFERENCES work_orders(id),
    type            VARCHAR(20) NOT NULL,
    quantity_change INTEGER     NOT NULL,
    note            VARCHAR(500),
    created_at      TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sm_part       ON stock_movements(part_id);
CREATE INDEX IF NOT EXISTS idx_sm_work_order ON stock_movements(work_order_id);

CREATE TABLE IF NOT EXISTS time_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT         NOT NULL REFERENCES work_orders(id),
    technician_id BIGINT         NOT NULL REFERENCES users(id),
    start_time    TIMESTAMP      NOT NULL,
    end_time      TIMESTAMP,
    hours_worked  NUMERIC(10, 2),
    notes         VARCHAR(1000),
    created_at    TIMESTAMPTZ    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tl_work_order ON time_logs(work_order_id);
CREATE INDEX IF NOT EXISTS idx_tl_technician ON time_logs(technician_id);

CREATE TABLE IF NOT EXISTS notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users(id),
    title      VARCHAR(200) NOT NULL,
    message    VARCHAR(1000),
    type       VARCHAR(30)  NOT NULL,
    is_read    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_notif_user ON notifications(user_id);

-- ==================== SEED USERS ====================
-- Passwords (bcryptjs cost 10):
--   manager1    → Manager@123
--   dispatcher1 → Dispatcher@123
--   tech1       → Tech@123
--   tech2       → Tech@123
--   customer1   → Customer@123

INSERT INTO users (username, password, first_name, last_name, email, phone, role, enabled, created_at, updated_at)
VALUES
    ('manager1',    '$2b$10$J68eQX7mPnZj/kXzTiEK8.yPfGjt1XUJpPZrEJv38MI.2pWPqqwAy', 'Alex',   'Morgan', 'alex.morgan@keystone.test',  '555-1001', 'MANAGER',    TRUE, NOW(), NOW()),
    ('dispatcher1', '$2b$10$AjDvH1qGnIvFehzxp9Zv7.vqYpq1JgGwjMMo5rvSxqz4.Z0/kVROq', 'Sam',    'Carter', 'sam.carter@keystone.test',   '555-1002', 'DISPATCHER', TRUE, NOW(), NOW()),
    ('tech1',       '$2b$10$/hm4g2B.3EkBu8qLX/jZKeFOG3xN3pUFCeHTZsz1HfjxESlWmZzCO', 'Jordan', 'Lee',    'jordan.lee@keystone.test',   '555-1003', 'TECHNICIAN', TRUE, NOW(), NOW()),
    ('tech2',       '$2b$10$/hm4g2B.3EkBu8qLX/jZKeFOG3xN3pUFCeHTZsz1HfjxESlWmZzCO', 'Casey',  'Kim',    'casey.kim@keystone.test',    '555-1004', 'TECHNICIAN', TRUE, NOW(), NOW()),
    ('customer1',   '$2b$10$cIKAgdwp1hxHBBHD5k4W8uPW7EYXSKbGY9I3x5wQI8uzN/bR7PE5m', 'Riley',  'Smith',  'riley.smith@acme.test',      '555-2001', 'CUSTOMER',   TRUE, NOW(), NOW())
ON CONFLICT (username) DO NOTHING;

-- ==================== SEED CUSTOMERS, SITES & PARTS ====================

INSERT INTO customers (name, contact_name, email, phone, address, user_id, created_at, updated_at)
SELECT 'Acme Manufacturing', 'Riley Smith', 'riley.smith@acme.test', '555-2001', '123 Industrial Way, Detroit, MI',
       u.id, NOW(), NOW()
FROM users u WHERE u.username = 'customer1'
ON CONFLICT (name) DO NOTHING;

INSERT INTO customers (name, contact_name, email, phone, address, created_at, updated_at)
VALUES
    ('Globex Logistics',   'Dana White',    'dana.white@globex.test', '555-3001', '88 Harbor Blvd, Chicago, IL',       NOW(), NOW()),
    ('Initech Facilities', 'Peter Gibbons', 'peter.g@initech.test',   '555-4001', '12 Corporate Plaza, Austin, TX',    NOW(), NOW())
ON CONFLICT (name) DO NOTHING;

INSERT INTO sites (customer_id, name, street_address, city, state, zip, country, contact_name, contact_phone, notes, created_at, updated_at)
SELECT c.id, 'Plant A', '123 Industrial Way', 'Detroit', 'MI', '48201', 'USA', 'Riley Smith', '555-2001', 'Main production facility', NOW(), NOW()
FROM customers c WHERE c.name = 'Acme Manufacturing'
ON CONFLICT DO NOTHING;

INSERT INTO sites (customer_id, name, street_address, city, state, zip, country, contact_name, contact_phone, notes, created_at, updated_at)
SELECT c.id, 'Plant B', '456 Foundry Rd', 'Toledo', 'OH', '43604', 'USA', 'Riley Smith', '555-2002', 'Secondary facility', NOW(), NOW()
FROM customers c WHERE c.name = 'Acme Manufacturing'
ON CONFLICT DO NOTHING;

INSERT INTO sites (customer_id, name, street_address, city, state, zip, country, contact_name, contact_phone, notes, created_at, updated_at)
SELECT c.id, 'Warehouse 7', '88 Harbor Blvd', 'Chicago', 'IL', '60601', 'USA', 'Dana White', '555-3001', 'East coast distribution', NOW(), NOW()
FROM customers c WHERE c.name = 'Globex Logistics'
ON CONFLICT DO NOTHING;

INSERT INTO sites (customer_id, name, street_address, city, state, zip, country, contact_name, contact_phone, notes, created_at, updated_at)
SELECT c.id, 'HQ Building', '12 Corporate Plaza', 'Austin', 'TX', '73301', 'USA', 'Peter Gibbons', '555-4001', 'Office campus', NOW(), NOW()
FROM customers c WHERE c.name = 'Initech Facilities'
ON CONFLICT DO NOTHING;

INSERT INTO parts (sku, name, description, unit_price, quantity_on_hand, reorder_level, created_at, updated_at)
VALUES
    ('ELEC-CONT-100', 'HVAC Control Board',       'Main control board for rooftop HVAC units',     349.99, 25,  5,  NOW(), NOW()),
    ('ELEC-MOT-250',  'Blower Motor 1HP',          'Single phase 1HP blower motor',                 189.50, 12,  4,  NOW(), NOW()),
    ('MECH-BLT-005',  'Drive Belt A-53',           'V-belt for air handler units',                   12.75, 80,  20, NOW(), NOW()),
    ('PLMB-VLV-120',  'Water Valve 1.2"',          'Electric actuated water control valve',           96.00, 6,   3,  NOW(), NOW()),
    ('SEC-SNS-001',   'Smoke Detector',            'Addressable photoelectric smoke detector',        45.25, 40,  10, NOW(), NOW()),
    ('ELEC-BRD-900',  'Furnace Ignition Board',    'Ignition control module for gas furnaces',       120.00, 3,   5,  NOW(), NOW()),
    ('MISC-FLT-010',  'Air Filter 20x20x1',        'MERV 8 pleated air filter',                       8.99, 150, 50, NOW(), NOW()),
    ('HVAC-RFR-404',  'Refrigerant R-404A (30lb)', 'Refrigerant cylinder for commercial units',      315.00, 8,   2,  NOW(), NOW())
ON CONFLICT (sku) DO NOTHING;

-- ==================== SEED WORK ORDERS ====================

INSERT INTO work_orders (work_order_number, customer_id, site_id, title, description, priority, status,
                         assigned_technician_id, created_by_id, scheduled_start, scheduled_end,
                         actual_start, actual_end, sla_due_at, sla_breached, created_at, updated_at, closed_at)
VALUES
    ('WO-000001',
     (SELECT id FROM customers WHERE name = 'Acme Manufacturing'),
     (SELECT id FROM sites     WHERE name = 'Plant A'),
     'Rooftop unit not cooling',
     'RTU-3 on production line losing cooling capacity, indoor temp rising.',
     'URGENT', 'NEW', NULL,
     (SELECT id FROM users WHERE username = 'dispatcher1'),
     '2026-08-16 09:00:00', '2026-08-16 13:00:00',
     NULL, NULL, '2026-08-16 13:00:00', FALSE,
     '2026-08-15 09:00:00', '2026-08-15 09:00:00', NULL),

    ('WO-000002',
     (SELECT id FROM customers WHERE name = 'Acme Manufacturing'),
     (SELECT id FROM sites     WHERE name = 'Plant B'),
     'Fan motor noise on air handler',
     'AHU-2 emitting grinding noise during operation, possible bearing wear.',
     'HIGH', 'ASSIGNED',
     (SELECT id FROM users WHERE username = 'tech1'),
     (SELECT id FROM users WHERE username = 'dispatcher1'),
     '2026-08-17 10:00:00', '2026-08-17 14:00:00',
     NULL, NULL, '2026-08-16 10:00:00', FALSE,
     '2026-08-15 09:30:00', '2026-08-15 09:35:00', NULL),

    ('WO-000003',
     (SELECT id FROM customers WHERE name = 'Acme Manufacturing'),
     (SELECT id FROM sites     WHERE name = 'Plant A'),
     'Water valve replacement',
     'Leaking electric water valve on chilled water loop, replacing with new valve.',
     'MEDIUM', 'IN_PROGRESS',
     (SELECT id FROM users WHERE username = 'tech1'),
     (SELECT id FROM users WHERE username = 'dispatcher1'),
     '2026-08-14 08:00:00', '2026-08-14 16:00:00',
     '2026-08-14 08:15:00', NULL, '2026-08-18 08:00:00', FALSE,
     '2026-08-13 10:00:00', '2026-08-14 08:15:00', NULL),

    ('WO-000004',
     (SELECT id FROM customers WHERE name = 'Initech Facilities'),
     (SELECT id FROM sites     WHERE name = 'HQ Building'),
     'Ignition board faulty',
     'Gas furnace ignition board showing fault code, heating intermittent. Waiting on part delivery.',
     'HIGH', 'ON_HOLD',
     (SELECT id FROM users WHERE username = 'tech2'),
     (SELECT id FROM users WHERE username = 'dispatcher1'),
     '2026-08-13 09:00:00', '2026-08-13 17:00:00',
     '2026-08-13 09:20:00', NULL, '2026-08-14 09:00:00', FALSE,
     '2026-08-12 14:00:00', '2026-08-13 11:00:00', NULL),

    ('WO-000005',
     (SELECT id FROM customers WHERE name = 'Globex Logistics'),
     (SELECT id FROM sites     WHERE name = 'Warehouse 7'),
     'Smoke detector testing',
     'Annual functional test of addressable smoke detectors on dock level.',
     'LOW', 'IN_PROGRESS',
     (SELECT id FROM users WHERE username = 'tech2'),
     (SELECT id FROM users WHERE username = 'dispatcher1'),
     '2026-08-14 13:00:00', '2026-08-14 18:00:00',
     '2026-08-14 13:30:00', NULL, '2026-08-21 13:00:00', FALSE,
     '2026-08-11 08:00:00', '2026-08-14 13:30:00', NULL),

    ('WO-000006',
     (SELECT id FROM customers WHERE name = 'Acme Manufacturing'),
     (SELECT id FROM sites     WHERE name = 'Plant A'),
     'Filter replacement routine',
     'Quarterly MERV 8 filter replacement across office air handlers.',
     'LOW', 'COMPLETED',
     (SELECT id FROM users WHERE username = 'tech1'),
     (SELECT id FROM users WHERE username = 'dispatcher1'),
     '2026-08-05 08:00:00', '2026-08-05 12:00:00',
     '2026-08-05 08:10:00', '2026-08-05 11:40:00', '2026-08-12 08:00:00', FALSE,
     '2026-08-04 09:00:00', '2026-08-05 11:40:00', NULL),

    ('WO-000007',
     (SELECT id FROM customers WHERE name = 'Globex Logistics'),
     (SELECT id FROM sites     WHERE name = 'Warehouse 7'),
     'Emergency refrigerant top-up',
     'Walk-in freezer low on refrigerant, emergency top-up performed.',
     'URGENT', 'CLOSED',
     (SELECT id FROM users WHERE username = 'tech2'),
     (SELECT id FROM users WHERE username = 'dispatcher1'),
     '2026-08-02 14:00:00', '2026-08-02 18:00:00',
     '2026-08-02 14:15:00', '2026-08-02 16:50:00', '2026-08-02 18:00:00', FALSE,
     '2026-08-02 13:30:00', '2026-08-03 09:00:00', '2026-08-03 09:00:00'),

    ('WO-000008',
     (SELECT id FROM customers WHERE name = 'Initech Facilities'),
     (SELECT id FROM sites     WHERE name = 'HQ Building'),
     'Thermostat not responding',
     'Second floor thermostat display blank, zone stuck heating.',
     'MEDIUM', 'NEW', NULL,
     (SELECT id FROM users WHERE username = 'dispatcher1'),
     '2026-08-18 09:00:00', '2026-08-18 13:00:00',
     NULL, NULL, '2026-08-19 09:00:00', FALSE,
     '2026-08-15 11:00:00', '2026-08-15 11:00:00', NULL)

ON CONFLICT (work_order_number) DO NOTHING;

-- ==================== STATUS HISTORY ====================

INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, NULL, 'NEW', NULL, '2026-08-15 09:00:00'::timestamptz, 'Work order created' FROM work_orders w WHERE w.work_order_number = 'WO-000001';

INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, NULL, 'NEW', NULL, '2026-08-15 09:30:00'::timestamptz, 'Work order created' FROM work_orders w WHERE w.work_order_number = 'WO-000002';
INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, 'NEW', 'ASSIGNED', (SELECT id FROM users WHERE username = 'dispatcher1'), '2026-08-15 09:35:00'::timestamptz, 'Assigned to Jordan Lee' FROM work_orders w WHERE w.work_order_number = 'WO-000002';

INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, NULL, 'NEW', NULL, '2026-08-13 10:00:00'::timestamptz, 'Work order created' FROM work_orders w WHERE w.work_order_number = 'WO-000003';
INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, 'NEW', 'ASSIGNED', (SELECT id FROM users WHERE username = 'dispatcher1'), '2026-08-13 10:05:00'::timestamptz, 'Assigned to Jordan Lee' FROM work_orders w WHERE w.work_order_number = 'WO-000003';
INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, 'ASSIGNED', 'IN_PROGRESS', (SELECT id FROM users WHERE username = 'tech1'), '2026-08-14 08:15:00'::timestamptz, 'Technician started work' FROM work_orders w WHERE w.work_order_number = 'WO-000003';

INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, NULL, 'NEW', NULL, '2026-08-12 14:00:00'::timestamptz, 'Work order created' FROM work_orders w WHERE w.work_order_number = 'WO-000004';
INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, 'NEW', 'ASSIGNED', (SELECT id FROM users WHERE username = 'dispatcher1'), '2026-08-12 14:10:00'::timestamptz, 'Assigned to Casey Kim' FROM work_orders w WHERE w.work_order_number = 'WO-000004';
INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, 'ASSIGNED', 'IN_PROGRESS', (SELECT id FROM users WHERE username = 'tech2'), '2026-08-13 09:20:00'::timestamptz, 'Technician started work' FROM work_orders w WHERE w.work_order_number = 'WO-000004';
INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, 'IN_PROGRESS', 'ON_HOLD', (SELECT id FROM users WHERE username = 'tech2'), '2026-08-13 11:00:00'::timestamptz, 'Waiting for part delivery' FROM work_orders w WHERE w.work_order_number = 'WO-000004';

INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, NULL, 'NEW', NULL, '2026-08-11 08:00:00'::timestamptz, 'Work order created' FROM work_orders w WHERE w.work_order_number = 'WO-000005';
INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, 'NEW', 'ASSIGNED', (SELECT id FROM users WHERE username = 'dispatcher1'), '2026-08-11 08:10:00'::timestamptz, 'Assigned to Casey Kim' FROM work_orders w WHERE w.work_order_number = 'WO-000005';
INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, 'ASSIGNED', 'IN_PROGRESS', (SELECT id FROM users WHERE username = 'tech2'), '2026-08-14 13:30:00'::timestamptz, 'Technician started work' FROM work_orders w WHERE w.work_order_number = 'WO-000005';

INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, NULL, 'NEW', NULL, '2026-08-04 09:00:00'::timestamptz, 'Work order created' FROM work_orders w WHERE w.work_order_number = 'WO-000006';
INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, 'NEW', 'ASSIGNED', (SELECT id FROM users WHERE username = 'dispatcher1'), '2026-08-04 09:05:00'::timestamptz, 'Assigned to Jordan Lee' FROM work_orders w WHERE w.work_order_number = 'WO-000006';
INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, 'ASSIGNED', 'IN_PROGRESS', (SELECT id FROM users WHERE username = 'tech1'), '2026-08-05 08:10:00'::timestamptz, 'Technician started work' FROM work_orders w WHERE w.work_order_number = 'WO-000006';
INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, 'IN_PROGRESS', 'COMPLETED', (SELECT id FROM users WHERE username = 'tech1'), '2026-08-05 11:40:00'::timestamptz, 'Job completed by technician' FROM work_orders w WHERE w.work_order_number = 'WO-000006';

INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, NULL, 'NEW', NULL, '2026-08-02 13:30:00'::timestamptz, 'Work order created' FROM work_orders w WHERE w.work_order_number = 'WO-000007';
INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, 'NEW', 'ASSIGNED', (SELECT id FROM users WHERE username = 'dispatcher1'), '2026-08-02 13:40:00'::timestamptz, 'Assigned to Casey Kim' FROM work_orders w WHERE w.work_order_number = 'WO-000007';
INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, 'ASSIGNED', 'IN_PROGRESS', (SELECT id FROM users WHERE username = 'tech2'), '2026-08-02 14:15:00'::timestamptz, 'Technician started work' FROM work_orders w WHERE w.work_order_number = 'WO-000007';
INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, 'IN_PROGRESS', 'COMPLETED', (SELECT id FROM users WHERE username = 'tech2'), '2026-08-02 16:50:00'::timestamptz, 'Job completed by technician' FROM work_orders w WHERE w.work_order_number = 'WO-000007';
INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, 'COMPLETED', 'CLOSED', (SELECT id FROM users WHERE username = 'manager1'), '2026-08-03 09:00:00'::timestamptz, 'Work order closed by manager' FROM work_orders w WHERE w.work_order_number = 'WO-000007';

INSERT INTO work_order_status_history (work_order_id, from_status, to_status, changed_by_id, changed_at, note)
SELECT w.id, NULL, 'NEW', NULL, '2026-08-15 11:00:00'::timestamptz, 'Work order created' FROM work_orders w WHERE w.work_order_number = 'WO-000008';

-- ==================== TIME LOGS ====================

INSERT INTO time_logs (work_order_id, technician_id, start_time, end_time, hours_worked, notes, created_at)
SELECT w.id, (SELECT id FROM users WHERE username = 'tech1'),
       '2026-08-05 08:10:00', '2026-08-05 11:40:00', 3.50, 'Replaced filters in 7 air handlers', NOW()
FROM work_orders w WHERE w.work_order_number = 'WO-000006';

INSERT INTO time_logs (work_order_id, technician_id, start_time, end_time, hours_worked, notes, created_at)
SELECT w.id, (SELECT id FROM users WHERE username = 'tech2'),
       '2026-08-02 14:15:00', '2026-08-02 16:50:00', 2.58, 'Topped up R-404A, leak test passed', NOW()
FROM work_orders w WHERE w.work_order_number = 'WO-000007';

INSERT INTO time_logs (work_order_id, technician_id, start_time, end_time, hours_worked, notes, created_at)
SELECT w.id, (SELECT id FROM users WHERE username = 'tech1'),
       '2026-08-14 08:15:00', NULL, NULL, 'Valve replacement in progress', NOW()
FROM work_orders w WHERE w.work_order_number = 'WO-000003';

-- ==================== STOCK MOVEMENTS ====================

INSERT INTO stock_movements (part_id, work_order_id, type, quantity_change, note, created_at)
SELECT p.id, NULL, 'INBOUND', 25,  'Initial stock load', NOW() FROM parts p WHERE p.sku = 'ELEC-CONT-100';
INSERT INTO stock_movements (part_id, work_order_id, type, quantity_change, note, created_at)
SELECT p.id, NULL, 'INBOUND', 12,  'Initial stock load', NOW() FROM parts p WHERE p.sku = 'ELEC-MOT-250';
INSERT INTO stock_movements (part_id, work_order_id, type, quantity_change, note, created_at)
SELECT p.id, NULL, 'INBOUND', 80,  'Initial stock load', NOW() FROM parts p WHERE p.sku = 'MECH-BLT-005';
INSERT INTO stock_movements (part_id, work_order_id, type, quantity_change, note, created_at)
SELECT p.id, NULL, 'INBOUND', 6,   'Initial stock load', NOW() FROM parts p WHERE p.sku = 'PLMB-VLV-120';
INSERT INTO stock_movements (part_id, work_order_id, type, quantity_change, note, created_at)
SELECT p.id, NULL, 'INBOUND', 40,  'Initial stock load', NOW() FROM parts p WHERE p.sku = 'SEC-SNS-001';
INSERT INTO stock_movements (part_id, work_order_id, type, quantity_change, note, created_at)
SELECT p.id, NULL, 'INBOUND', 3,   'Initial stock load', NOW() FROM parts p WHERE p.sku = 'ELEC-BRD-900';
INSERT INTO stock_movements (part_id, work_order_id, type, quantity_change, note, created_at)
SELECT p.id, NULL, 'INBOUND', 150, 'Initial stock load', NOW() FROM parts p WHERE p.sku = 'MISC-FLT-010';
INSERT INTO stock_movements (part_id, work_order_id, type, quantity_change, note, created_at)
SELECT p.id, NULL, 'INBOUND', 8,   'Initial stock load', NOW() FROM parts p WHERE p.sku = 'HVAC-RFR-404';

INSERT INTO stock_movements (part_id, work_order_id, type, quantity_change, note, created_at)
SELECT p.id, w.id, 'OUTBOUND', -4, 'Filters used on WO-000006', '2026-08-05 11:40:00'::timestamptz
FROM parts p CROSS JOIN work_orders w
WHERE p.sku = 'MISC-FLT-010' AND w.work_order_number = 'WO-000006';

INSERT INTO stock_movements (part_id, work_order_id, type, quantity_change, note, created_at)
SELECT p.id, w.id, 'OUTBOUND', -2, 'Valves used on WO-000003', '2026-08-14 09:00:00'::timestamptz
FROM parts p CROSS JOIN work_orders w
WHERE p.sku = 'PLMB-VLV-120' AND w.work_order_number = 'WO-000003';

-- ==================== NOTIFICATIONS ====================

INSERT INTO notifications (user_id, title, message, type, is_read, created_at)
SELECT u.id, 'New assignment', 'WO-000002 (Fan motor noise) has been assigned to you.', 'ASSIGNMENT', FALSE, '2026-08-15 09:35:00'::timestamptz
FROM users u WHERE u.username = 'tech1';

INSERT INTO notifications (user_id, title, message, type, is_read, created_at)
SELECT u.id, 'Work started', 'You started WO-000003 (Water valve replacement).', 'STATUS_CHANGE', FALSE, '2026-08-14 08:15:00'::timestamptz
FROM users u WHERE u.username = 'tech1';

INSERT INTO notifications (user_id, title, message, type, is_read, created_at)
SELECT u.id, 'SLA at risk', 'WO-000001 (Rooftop unit not cooling) is due within 4 hours.', 'SLA_REMINDER', FALSE, '2026-08-16 09:00:00'::timestamptz
FROM users u WHERE u.username = 'dispatcher1';

INSERT INTO notifications (user_id, title, message, type, is_read, created_at)
SELECT u.id, 'Low stock alert', 'Part ELEC-BRD-900 (Furnace Ignition Board) is below reorder level.', 'STOCK_LOW', FALSE, '2026-08-15 08:00:00'::timestamptz
FROM users u WHERE u.username = 'manager1';

-- =============================================================
-- Done! Your database is ready.
-- =============================================================
