-- Keystone Field Service Management - initial schema
CREATE SEQUENCE work_order_number_seq START WITH 100;

CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(100) NOT NULL UNIQUE,
    password     VARCHAR(255) NOT NULL,
    first_name   VARCHAR(100) NOT NULL,
    last_name    VARCHAR(100) NOT NULL,
    email        VARCHAR(150) NOT NULL UNIQUE,
    phone        VARCHAR(30),
    role         VARCHAR(30) NOT NULL,
    enabled      BOOLEAN NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE customers (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(200) NOT NULL UNIQUE,
    contact_name VARCHAR(100),
    email        VARCHAR(150),
    phone        VARCHAR(30),
    address      VARCHAR(300),
    user_id      BIGINT REFERENCES users(id),
    created_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_customers_user UNIQUE (user_id)
);

CREATE TABLE sites (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    BIGINT NOT NULL REFERENCES customers(id),
    name           VARCHAR(200) NOT NULL,
    street_address VARCHAR(200) NOT NULL,
    city           VARCHAR(100) NOT NULL,
    state          VARCHAR(50),
    zip            VARCHAR(20),
    country        VARCHAR(100),
    contact_name   VARCHAR(100),
    contact_phone  VARCHAR(30),
    notes          VARCHAR(500),
    created_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_sites_customer ON sites(customer_id);

CREATE TABLE work_orders (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_number      VARCHAR(30) NOT NULL UNIQUE,
    customer_id            BIGINT NOT NULL REFERENCES customers(id),
    site_id                BIGINT NOT NULL REFERENCES sites(id),
    title                  VARCHAR(200) NOT NULL,
    description            VARCHAR(2000),
    priority               VARCHAR(20) NOT NULL,
    status                 VARCHAR(20) NOT NULL DEFAULT 'NEW',
    assigned_technician_id BIGINT REFERENCES users(id),
    created_by_id          BIGINT REFERENCES users(id),
    scheduled_start        TIMESTAMP(6),
    scheduled_end          TIMESTAMP(6),
    actual_start           TIMESTAMP(6),
    actual_end             TIMESTAMP(6),
    sla_due_at             TIMESTAMP(6),
    sla_breached           BOOLEAN NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at             TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    closed_at              TIMESTAMP(6) WITH TIME ZONE
);
CREATE INDEX idx_wo_status ON work_orders(status);
CREATE INDEX idx_wo_customer ON work_orders(customer_id);
CREATE INDEX idx_wo_technician ON work_orders(assigned_technician_id);

CREATE TABLE work_order_status_history (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id  BIGINT NOT NULL REFERENCES work_orders(id),
    from_status    VARCHAR(20),
    to_status      VARCHAR(20) NOT NULL,
    changed_by_id  BIGINT REFERENCES users(id),
    changed_at     TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    note           VARCHAR(1000)
);
CREATE INDEX idx_woh_work_order ON work_order_status_history(work_order_id);

CREATE TABLE parts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku              VARCHAR(50) NOT NULL UNIQUE,
    name             VARCHAR(200) NOT NULL,
    description      VARCHAR(1000),
    unit_price       NUMERIC(19, 2) NOT NULL,
    quantity_on_hand INTEGER NOT NULL DEFAULT 0,
    reorder_level    INTEGER NOT NULL DEFAULT 0,
    created_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE stock_movements (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id         BIGINT NOT NULL REFERENCES parts(id),
    work_order_id   BIGINT REFERENCES work_orders(id),
    type            VARCHAR(20) NOT NULL,
    quantity_change INTEGER NOT NULL,
    note            VARCHAR(500),
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_sm_part ON stock_movements(part_id);
CREATE INDEX idx_sm_work_order ON stock_movements(work_order_id);

CREATE TABLE time_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id BIGINT NOT NULL REFERENCES work_orders(id),
    technician_id BIGINT NOT NULL REFERENCES users(id),
    start_time    TIMESTAMP(6) NOT NULL,
    end_time      TIMESTAMP(6),
    hours_worked  NUMERIC(10, 2),
    notes         VARCHAR(1000),
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_tl_work_order ON time_logs(work_order_id);
CREATE INDEX idx_tl_technician ON time_logs(technician_id);

CREATE TABLE notifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id),
    title      VARCHAR(200) NOT NULL,
    message    VARCHAR(1000),
    type       VARCHAR(30) NOT NULL,
    is_read    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_notif_user ON notifications(user_id);
